# Managed by puppet
export HISTCONTROL=ignoreboth
export HISTSIZE=5000
export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] \$ '
export EDITOR=vim
export PAGER='less -FXI'

alias less='less -FXI'

export KUBECONFIG=/etc/kubernetes/admin.conf
source <(kubectl completion bash)
